# Generated by Django 3.0.7 on 2020-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20200616_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_10',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_11',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_12',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_13',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_14',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_15',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_16',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_17',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_18',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_19',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_2',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_3',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_4',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_5',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_6',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_7',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_8',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_003_9',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_1',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_10',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_11',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_12',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_13',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_14',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_15',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_16',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_17',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_18',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_2',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_3',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_4',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_5',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_6',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_7',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_8',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='p11_004_9',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
